from harvest_osm import harvest_osm
import time

cities = [
    "New York, NY",
    "Los Angeles, CA",
    "Chicago, IL",
    "Phoenix, AZ",
    "Philadelphia, PA",
    "San Antonio, TX",
    "San Diego, CA",
    "Dallas, TX",
    "San Jose, CA",
    "Austin, TX",
    "Jacksonville, FL",
    "Fort Worth, TX",
    "Columbus, OH",
    "Charlotte, NC",
    "Indianapolis, IN",
    "San Francisco, CA",
    "Seattle, WA",
    "Denver, CO",
    "Oklahoma City, OK",
    "Nashville, TN",
    "El Paso, TX",
    "Washington, DC",
    "Boston, MA",
    "Las Vegas, NV",
    "Portland, OR",
    "Louisville, KY",
    "Memphis, TN",
    "Detroit, MI",
    "Baltimore, MD",
    "Milwaukee, WI",
    "Albuquerque, NM",
    "Tucson, AZ",
    "Fresno, CA",
    "Sacramento, CA",
    "Mesa, AZ",
    "Kansas City, MO",
    "Atlanta, GA",
    "Colorado Springs, CO",
    "Miami, FL",
    "Raleigh, NC",
    "Omaha, NE",
    "Long Beach, CA",
    "Virginia Beach, VA",
    "Oakland, CA",
    "Minneapolis, MN",
    "Tampa, FL",
    "Tulsa, OK",
    "Arlington, TX",
    "Wichita, KS",
    "Bakersfield, CA",
    "Aurora, CO",
    "New Orleans, LA",
    "Cleveland, OH",
    "Anaheim, CA",
    "Honolulu, HI",
    "Henderson, NV",
    "Stockton, CA",
    "Riverside, CA",
    "Lexington, KY",
    "Corpus Christi, TX",
    "Orlando, FL",
    "Irvine, CA",
    "Cincinnati, OH",
    "Santa Ana, CA",
    "Newark, NJ",
    "Saint Paul, MN",
    "Pittsburgh, PA",
    "Jersey City, NJ",
    "Lincoln, NE",
    "Durham, NC",
    "Plano, TX",
    "Anchorage, AK",
    "Chandler, AZ",
    "St. Louis, MO",
    "Gilbert, AZ",
    "Reno, NV",
    "North Las Vegas, NV",
    "Madison, WI",
    "Glendale, AZ",
    "Buffalo, NY",
    "Chesapeake, VA",
    "Scottsdale, AZ",
    "Garland, TX",
    "Irving, TX",
    "Hialeah, FL",
    "Fremont, CA",
    "Boise, ID",
    "Richmond, VA",
    "Baton Rouge, LA",
    "Spokane, WA",
    "Des Moines, IA",
    "Tacoma, WA",
    "San Bernardino, CA",
    "Modesto, CA",
    "Fontana, CA",
    "Santa Clarita, CA",
    "Birmingham, AL",
    "Oxnard, CA",
    "Fayetteville, NC",
    "Rochester, NY",
    "Moreno Valley, CA",
    "Salt Lake City, UT",
    "Amarillo, TX",
    "Fort Lauderdale, FL"
]

def run_bulk():
    print(f"🚀 Starting Bulk Harvest for {len(cities)} cities...")
    
    for i, city in enumerate(cities):
        print(f"\n[{i+1}/{len(cities)}] Processing: {city}")
        try:
            harvest_osm(city)
        except Exception as e:
            print(f"FAILED {city}: {e}")
        
        # Friendly sleep to avoid hammering
        time.sleep(2)

if __name__ == "__main__":
    run_bulk()
